<div id="contentTable">
    <div class="menu-content">
        <?php print_unescaped($this->inc('navigation/toggle')); ?>
        <a href="<?php echo($_['url']['index']); ?>"><span class="material-symbols-outlined">home</span></a>
        <span class="material-symbols-outlined">chevron_right</span>
        <span><?php p($l->t('Quote'));?></span>
        <span class="material-symbols-outlined">chevron_right</span>
        <button style="margin-left:3px;" type="button"  id="newDevis"><?php p($l->t('Add quote'));?></button>
    </div>
    <table id="devis" class="display tabledt">
        <thead>
            <tr>
                <th class="help-heading" title="<?php p($l->t('Internal identifier of the Nextcloud user associated with the quote. It is generated by the application and is not a legal quote number.'));?>"><?php p($l->t('ID'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the date on which the quote is issued. In France, the issue date is mandatory when a quote is legally required.'));?>"><?php p($l->t('Quote date'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter a clear and unique business reference for the quote so it can be identified and linked to an invoice.'));?>"><?php p($l->t('Quote number'));?></th>
                <th class="help-heading" title="<?php p($l->t('Select the customer receiving the quote. For French mandatory quotes, the customer name and address must be stated.'));?>"><?php p($l->t('Customer quote'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the revision number of the quote, for example 1.0 or 2.0. Increase it when issuing a materially revised quote.'));?>"><?php p($l->t('Version'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the current quote status, for example Draft, Sent, Accepted, Rejected or Expired. An accepted quote can become binding evidence of the agreement.'));?>"><?php p($l->t('Status'));?></th>
                <th class="help-heading" title="<?php p($l->t('Use the actions menu to open, download, duplicate or delete the quote. Keep accepted quotes for the retention period applicable to your business.'));?>"><?php p($l->t('Actions'));?></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
