<div id="contentTable">
    <div class="menu-content">
        <a href="<?php echo($_['url']['index']); ?>"><span class="material-symbols-outlined">home</span></a>
        <span class="material-symbols-outlined">chevron_right</span>
        <span><?php p($l->t('Invoice'));?></span>
        <span class="material-symbols-outlined">chevron_right</span>
        <button style="margin-left:3px;" type="button" id="newInvoice"><?php p($l->t('Add invoice'));?></button>
    </div>
    <table id="facture" class="display tabledt">
        <thead>
            <tr>
                <th class="help-heading" title="<?php p($l->t('Internal identifier of the Nextcloud user associated with the invoice. It is generated by the application and is not the legal invoice number.'));?>"><?php p($l->t('ID'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the invoice number. In France, it is mandatory and must be unique within a chronological, continuous and gap-free sequence.'));?>"><?php p($l->t('Invoice number'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the actual delivery date or the date on which the service was completed. This date is mandatory on French invoices.'));?>"><?php p($l->t('Date of service'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the payment due date. French business invoices must state the due date or applicable payment terms.'));?>"><?php p($l->t('Payment date'));?></th>
                <th class="help-heading" title="<?php p($l->t('Select the expected payment method using the structured code: cash, cheque, credit transfer, payment card or SEPA credit transfer.'));?>"><?php p($l->t('Means of payment'));?></th>
                <th class="help-heading" title="<?php p($l->t('Select the quote from which this invoice is created. This links the invoice to its accepted commercial terms and customer.'));?>"><?php p($l->t('Associated quote'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the internal document revision. Do not reuse or alter the legal number of an issued French invoice; issue a corrective document when required.'));?>"><?php p($l->t('Version'));?></th>
                <th class="help-heading" title="<?php p($l->t('Enter the payment status, for example Pending, Paid, Partially paid, Overdue or Cancelled. Keep it consistent with the payment due date.'));?>"><?php p($l->t('Status'));?></th>
                <th class="help-heading" title="<?php p($l->t('Use the actions menu to open, download, duplicate or delete the invoice. In France, issued invoices are accounting records and must be retained; do not delete them to correct an error.'));?>"><?php p($l->t('Actions'));?></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
